### ISSUE TITLE
[Bug] Plugin can't start

### ISSUE THREAD

**Issue by veldik** [Oribuin/ChatEmojis#2]
Plugin version: `VERSION 1.1.0`
![image](https://user-images.githubusercontent.com/37436112/88155720-bd8a8d00-cc08-11ea-8f1b-3ee9bfbe9d15.png)
```
[10:42:20 ERROR]: Could not load 'plugins/ChatEmojis-1.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.1.jar:git-Paper-91]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-91]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-91]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.zip.ZipException: invalid END header (bad central directory offset)
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_242]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_242]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_242]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_242]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.1.jar:git-Paper-91]
... 6 more
```
Server Version:
```
[10:51:10 INFO]: This server is running Paper version git-Paper-91 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[10:51:10 INFO]: Checking version, please wait...
[10:51:10 INFO]: Previous version: git-Paper-89 (MC: 1.16.1)
[10:51:10 INFO]: You are 17 version(s) behind
```

**Comment by veldik** [comment]
Plugin can start without problems:
```
[16:22:41 INFO]: [ChatEmojis] Enabling ChatEmojis v1.1.1
```
