### ISSUE TITLE
[BUG] /emoji don't work

### ISSUE THREAD

**Issue by veldik** [Oribuin/ChatEmojis#4]
Command for list of emojis don't working.

```
[15:07:12 INFO]: Velda_ issued server command: /emoji
[15:07:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'emoji' in plugin ChatEmojis v1.1.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-91]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-91]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-91]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-91]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at xyz.oribuin.chatemojis.utils.StringPlaceholders.apply(StringPlaceholders.java:46) ~[?:?]
at xyz.oribuin.chatemojis.guis.MainMenu.format(MainMenu.java:81) ~[?:?]
at xyz.oribuin.chatemojis.guis.MainMenu.lambda$buildGui$7(MainMenu.java:214) ~[?:?]
at dev.rosewood.guiframework.framework.gui.screen.FrameworkScreen.populateInventory(FrameworkScreen.java:364) ~[?:?]
at dev.rosewood.guiframework.framework.gui.screen.FrameworkScreen.getInventory(FrameworkScreen.java:321) ~[?:?]
at dev.rosewood.guiframework.framework.gui.FrameworkContainer.openFor(FrameworkContainer.java:69) ~[?:?]
at dev.rosewood.guiframework.framework.gui.FrameworkContainer.openFor(FrameworkContainer.java:79) ~[?:?]
at xyz.oribuin.chatemojis.guis.MainMenu.openGui(MainMenu.java:44) ~[?:?]
at xyz.oribuin.chatemojis.cmds.CmdEmoji.executeCommand(CmdEmoji.java:149) ~[?:?]
at xyz.oribuin.chatemojis.cmds.OriCommand.onCommand(OriCommand.java:35) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-91]
... 18 more
```

**Comment by veldik** [comment]
It was our problem. We don't update emoji list.
